export const bestiesContent = {
  logo: "👯‍♀️",
  editEmoji: "✏️",
  starEmoji: "⭐️",
  homeEmoji: "🏠",
  cancel: "cancel",
  delete: "delete",
  submitButtonText: "post",
  submitButtonLoadingText: "posting...",
  auth: {
    appName: "besties 👯‍♀️",
    createAnAccount: "create an account",
    dontHaveAnAccount: "don't have an account?",
    emailAddress: "email",
    error: "error",
    forgotPassword: "forgot password?",
    fullName: "name",
    goToLoginMessage: "already a user?",
    goToSignupMessage: "no account yet?",
    hideEmoji: "🙈",
    invalidEmailAddress: "email address is not valid",
    invalidPassword: "password must be at least 8 characters long",
    loggingIn: "signing In",
    login: "sign in",
    loginSuccess: "you are logged in",
    loginFailure: "logging in failed",
    logInToYourAccount: "log in to your account",
    logOutSuccess: "successfully logged out",
    orContinueWith: "or continue with",
    password: "password",
    pleaseEnterAnEmailAddress: "please enter an email address",
    pleaseEnterUsername: "please enter a username",
    pleaseEnterPassword: "please enter password",
    pleaseEnterName: "please enter your full name",
    rememberMe: "remember me",
    showEmoji: "👀",
    signingUp: "signing up",
    signInToYourAccount: "sign in to your account",
    signup: "sign up",
    signupFailed: "signing Up failed",
    signupSubtitle: "to enjoy all of our cool features ✌️",
    signupSuccess: "account created",
    username: "username",
    usernameMinLength: "username must be at least 1 characters long",
    fullNameMinLength: "name must be at least 1 character long",
    usernameAlphaNumeric: "username must be alphanumeric",
    fullNameAlphaNumeric: "name must be alphanumeric",
    usernameTaken: "username already exists",
  },
  navBar: {
    highestRated: "⭐️ highest rated",
    home: "home",
    logOut: "🚪🚶log out",
    mostPopular: "🩷 most popular",
    seeAllUsers: "👥 make friends",
    goToProfile: "👤 my profile",
    newReview: "review",
  },
  reviewForm: {
    revieweeField: "who are you reviewing?",

    reviewField: "what do we need to know?",
    fieldRequired: "required",
    reviewMinLength: "review must be at least 1 character long",
    reviewMaxLength: "review must be less than 280 characters",
  },
  commentForm: { commentField: "write a comment" },
  post: {
    reviewed: "👉",
    deleteReviewHeading: "delete review",
    deleteReviewBody: "are you sure?",
    ago: "ago",
  },
  activity: {
    noActivity: "no activity yet...",
  },
  search: {
    search: "search",
  },
  lists: {
    highestRatedHeading: "best people",
  },
  home: { homeScreenImage: "", heading: "" },
};
