export const CONTENT = {
  logo: "👯‍♂️",
  heartEmoji: "🩷",
  starEmoji: "⭐️",
  AUTH: {
    appName: "besties 👯‍♂️",
    createAnAccount: "create an account",
    dontHaveAnAccount: "don't have an account?",
    emailAddress: "email",
    error: "error",
    forgotPassword: "forgot password?",
    fullName: "full name",
    goToLoginMessage: "already a user?",
    goToSignupMessage: "no account yet?",
    invalidEmailAddress: "email address is not valid",
    invalidPassword: "password must be at least 8 characters long",
    loggingIn: "signing In",
    login: "sign in",
    loginSuccess: "You are logged in",
    logInToYourAccount: "log in to your account",
    logOutSuccess: "successfully logged out",
    orContinueWith: "or continue with",
    password: "password",
    pleaseEnterAnEmailAddress: "please enter an email address",
    pleaseEnterPassword: "please enter password",
    rememberMe: "remember me",
    signingUp: "signing up",
    signInToYourAccount: "sign in to your account",
    signup: "sign up",
    signupFailed: "signing Up failed",
    signupSubtitle: "to enjoy all of our cool features ✌️",
    signupSuccess: "account created",
    username: "username",
    usernameTaken: "username already exists",
  },
  NAVBAR: {
    highestRated: "highest rated",
    home: "home",
    logOut: "log out",
    mostPopular: "most popular",
    seeAllUsers: "👤 make friends",
    myProfile: "my profile",
  },
};
